### ISSUE TITLE
undefined method `parse_url_with_auth' at em-rest-client/em_http_request.rb:13

### ISSUE THREAD

**Issue by mazimeng** [railsware/em-rest-client#1]
hi. I'm using this with restclient 2.0.0 but it throws this "undefined method `parse_url_with_auth'" at em-rest-client/em_http_request.rb:13

I think they made the #parse_url_with_auth private and also renamed it. And they initialize the @uri in RestClient::Request's constructor so probably no need to build @uri in #execute.

**Comment by ayanko** [comment]
@mazimeng 
Try `v0.1.0`
Now we support both rest-client versions (v1.8.x & v2.0.x)

**Comment by ayanko** [comment]
I assume issue is resolved.
